### ISSUE TITLE
關於職骰指令判斷

### ISSUE THREAD

**Issue by wei840220** [hktrpg/TG.line.Discord.Roll.Bot#21]
您好，不知道相關建議在這裡提出恰不恰當，如有冒昧還請多包涵
只是單純認為 **10d100<=80** 這個指令目前的結果有些微妙
理解上會以為是 **10 1d100<=80**
但卻變成是骰十次一百面骰的總和判斷是否小於 80
雖然也可以用 **10 1d100<=80** 取代這個指令
但如果出現的不是十次骰的總和，而是成功次數的總和（成功幾次）
個人認為或許會比較理想，在此提供建議

**Comment by zeteticl** [comment]
你好,感謝你的建議,我思考過你說法
但因為有很多的遊戲系統 
例如DND 採用 Xd10>= DC
日系忍神 2D6>= X
這麼加總然後計算的方法
所以 算是約定俗成吧
不可能使用非加總的方式

另外
在骰表中其實有你所說的骰法
指令是B取代D
5B10： 不加總的擲骰 會進行小至大排序  
 5B10 9： 如上,另外計算其中有多少粒大於9  

現在我希望dicebot更多功能
歡迎提出更多意見

**Comment by zeteticl** [comment]
簡單說 因為全世界的dicebot 都是這表達方式
所以要這樣ww

**Comment by wei840220** [comment]
原來如此，因為主要是玩 CoC 所以沒有考慮過其他遊戲系統！
因為我之前慣用的是 Sidekick 這個 dicebot，而對於 **10d100<=80** 
它會給出如下格式的結果：
10d100<=80  = (24 9 55 ~~92~~ 61 ~~86~~ 24 25 53 2, 8 successes) = 8
對我來說是比較方便的～

之前也有注意過 5b10 之類的語法，不過確實如你所說，因為只計算大於所以對我來說不太實用
而且這方面也不需要由小至大的排序XD （有些判定上不太公平，這就是題外話了）
也很謝謝你的耐心回應

**Comment by zeteticl** [comment]
因為我那邊主流是使用日本凍豆腐擲骰系統
所以寫BOT 時
都是跟從他們的慣例🤔
我找時間加一加

**Comment by zeteticl** [comment]
5B10： 不加總的擲骰  
 5B10<>=x ： 如上,另外計算其中有多少粒大於小於X  
 5B10 (D)x ： 如上,用空格取代, 即大於, 使用D即小於 
 即 5B10 5 相當於 5B10>=5  5B10 D5 相當於 5B10<=5

**Comment by wei840220** [comment]
謝謝你如此耐心替我解決了這個小困擾！這個 Issue 也可以關閉了
