### ISSUE TITLE
跑团log记录功能

### ISSUE THREAD

**Issue by alrcatraz** [hktrpg/TG.line.Discord.Roll.Bot#598]
在官方使用教学页面没有看到这个功能，但是如果结束后想要整理跑团记录又不想搭进去无关的对话的话，这个功能很有用，恳请大大们有空可以加一下

**Comment by zeteticl** [comment]
https://bothelp.hktrpg.com/hktrpg-guan-fang-shi-yong-jiao-xue/xi-tong-gong-ju/discord-bin-dao-liao-tian-ji-lu-shu-chu-gong-ju

使用export 功能?

**Comment by alrcatraz** [comment]
原来如此，是我没有注意到
但是这个功能有“开始记录”和“结束记录”的指令吗？我觉得或许有这两个功能会比直接输出该频道的全部聊天记录更有效率

从 Windows 版邮件发送

发件人: Sad
发送时间: 2022年8月15日 13:12
收件人: hktrpg/TG.line.Discord.Roll.Bot
抄送: alrcatraz; Author
主题: Re: [hktrpg/TG.line.Discord.Roll.Bot] 跑团log记录功能 (Issue #598)

https://bothelp.hktrpg.com/hktrpg-guan-fang-shi-yong-jiao-xue/xi-tong-gong-ju/discord-bin-dao-liao-tian-ji-lu-shu-chu-gong-ju
使用export 功能?

**Comment by zeteticl** [comment]
https://bothelp.hktrpg.com/hktrpg-guan-fang-shi-yong-jiao-xue/xi-tong-gong-ju/discord-bin-dao-liao-tian-ji-lu-shu-chu-gong-ju

請看功能說明

**Comment by alrcatraz** [comment]
您好，谢谢您的提醒
我已经注意到了存在.discord指令可以导出聊天记录，但是就如我前一篇回复所说的，从介绍页面来看，这一指令似乎并不包含“开始记录”和“结束记录”的功能
 
如上，或许是我没有注意到这些附属指令如何使用，如果是这样，烦请教导我一下这个指令的更进一步用法
我和我的朋友计划从QQ转移到discord来玩，我想我们可能会在一个固定的频道持续多个团之类的，这时如果没有可选的记录和导出一部分跑团记录的功能的话，就需要跳过大量的记录，我想这会是一个相当耗费时间的问题
所以，如果没有这个功能，我建议或许加上这个功能会有不错的应用前景

感谢你们百忙之中不嫌弃我的叨扰，阅读和回复我的消息，大大们辛苦了

**Comment by zeteticl** [comment]
感謝你的建議，但「開始/結束記錄」類的功能比較消耗資源，
我亦相信，一個有機會出錯的事，就必然會出錯，如果KP需要不斷開關，總有一天會忘記，而導致失去部分跑團紀錄。
而Discord 是一個非常容易建構新頻道的平台
我強烈建議，使用Discord跑團時，開一個頻道合集(Category)，
然後裡面有「第一天」，「第二天」，「第三天」，「場外話」的Channel
讓玩家自行在適合的頻道發言，而不要遊戲內外言論混合，這樣比較好整理團錄。

但如果你真的很想要這類功能
你可以在issues裡，使用
[Category](https://github.com/hktrpg/TG.line.Discord.Roll.Bot/issues/new?assignees=&labels=enhancement&template=---------.md&title=)
再說明你的要求

**Comment by alrcatraz** [comment]
感谢您的答复，或许这也是一个不错的解决方案，我会先和朋友们试一试的
我们从QQ来，因为QQ群并不如频道那般方便，因此这个习惯也继承了下来……如果依然觉得这个功能还是有其必要性的话，我会再提意见的。谢谢

从 Windows 版邮件发送

发件人: Sad
发送时间: 2022年8月19日 11:08
收件人: hktrpg/TG.line.Discord.Roll.Bot
抄送: alrcatraz; Author
主题: Re: [hktrpg/TG.line.Discord.Roll.Bot] 跑团log记录功能 (Issue #598)

感謝你的建議，但「開始/結束記錄」類的功能比較消耗資源，
我亦相信，一個有機會出錯的事，就必然會出錯，如果KP需要不斷開關，總有一天會忘記，而導致失去部分跑團紀錄。
而Discord 是一個非常容易建構新頻道的平台
我強烈建議，使用Discord跑團時，開一個頻道合集(Category)，
然後裡面有「第一天」，「第二天」，「第三天」，「場外話」的Channel
讓玩家自行在適合的頻道發言，而不要遊戲內外言論混合，這樣比較好整理團錄。
但如果你真的很想要這類功能
你可以在issues裡，使用
Category
再說明你的要求

**Comment by alrcatraz** [comment]
您好，谢谢您的提醒
我已经注意到了存在.discord指令可以导出聊天记录，但是就如我前一篇回复所说的，从介绍页面来看，这一指令似乎并不包含“开始记录”和“结束记录”的功能

如上，或许是我没有注意到这些附属指令如何使用，如果是这样，烦请教导我一下这个指令的更进一步用法
我和我的朋友计划从QQ转移到discord来玩，我想我们可能会在一个固定的频道持续多个团之类的，这时如果没有可选的记录和导出一部分跑团记录的功能的话，就需要跳过大量的记录，我想这会是一个相当耗费时间的问题
所以，如果没有这个功能，我建议或许加上这个功能会有不错的应用前景

感谢你们百忙之中不嫌弃我的叨扰，阅读和回复我的消息，大大们辛苦了

从 Windows 版邮件发送

发件人: Sad
发送时间: 2022年8月16日 2:43
收件人: hktrpg/TG.line.Discord.Roll.Bot
抄送: alrcatraz; Author
主题: Re: [hktrpg/TG.line.Discord.Roll.Bot] 跑团log记录功能 (Issue #598)

https://bothelp.hktrpg.com/hktrpg-guan-fang-shi-yong-jiao-xue/xi-tong-gong-ju/discord-bin-dao-liao-tian-ji-lu-shu-chu-gong-ju
請看功能說明
